[package]
name = "phrust"
version = "0.0.0"

[lib]
name = "phrust"
crate-type = ["rlib", "staticlib"]

[profile.release]
debug = true

[dependencies]
num_cpus = "0.2.6"
glfw = "*"
gl = "*"
time = "*"
rand = "*"
